In [1]:
import numpy as np

# Elementwise Operations

**1. Basic Operations**

**with scalars**

In [2]:
a = np.array([1, 2, 3, 4]) #create an array

a + 1

array([2, 3, 4, 5])

In [4]:
l = [1,2,3,4]
l+1

TypeError: can only concatenate list (not "int") to list

In [5]:
l+l

[1, 2, 3, 4, 1, 2, 3, 4]

In [6]:
print(a)
a ** 2

[1 2 3 4]


array([ 1,  4,  9, 16])

**All arithmetic operates elementwise**

In [7]:
b = np.ones(4)
print(a)
print(b)
a + b

[1 2 3 4]
[1. 1. 1. 1.]


array([2., 3., 4., 5.])

In [8]:
a * b

array([1., 2., 3., 4.])

In [10]:
# Matrix multiplication

c = np.diag([1, 2, 3])
print(c)
print('*'*30)
print(c * c)
print("*****************")
print(c.dot(c))

[[1 0 0]
 [0 2 0]
 [0 0 3]]
******************************
[[1 0 0]
 [0 4 0]
 [0 0 9]]
*****************
[[1 0 0]
 [0 4 0]
 [0 0 9]]


In [10]:
c1 = np.array([[1,2,1],[0,1,0],[2,3,4]])
c1


array([[1, 2, 1],
       [0, 1, 0],
       [2, 3, 4]])

In [11]:
c1.shape

(3, 3)

In [12]:
c2 = np.array([[2,5],[6,7],[1,8]])
c2

array([[2, 5],
       [6, 7],
       [1, 8]])

In [9]:
1*2 + 2*6 + 1*1

15

In [32]:
c2.shape

(3, 2)

In [33]:
# (3,3) * (3,2) = (3,2)

In [13]:
c1.dot(c2)

array([[15, 27],
       [ 6,  7],
       [26, 63]])

**comparisions**

In [12]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [14]:
a >= b

array([False,  True,  True,  True])

In [15]:
#array-wise comparisions
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])

np.array_equal(a, b)

False

In [ ]:
np.array_equal(a, c)

True

**Logical Operations**

In [24]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

np.logical_or(a, b)

array([ True,  True,  True, False])

In [25]:
np.logical_and(a, b)

array([ True, False, False, False])

**Transcendental functions:**

In [16]:
a = np.arange(5)
print(a)
np.cos(a)

[0 1 2 3 4]


array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [17]:
np.log(a)

<ipython-input-17-89b6b8e53c58>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [28]:
np.exp(a)   #evaluates e^x for each element in a given input

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

**Shape Mismatch**

In [29]:
a = np.arange(4)
print(a)
a + np.array([1, 2])

[0 1 2 3]


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

# Basic Reductions

**computing sums**

In [18]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [19]:
#sum by rows and by columns

x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [20]:
x.sum(axis=0)   #columns first dimension

array([3, 3])

In [21]:
x.sum(axis=1)  #rows (second dimension)

array([2, 4])

In [22]:
x.sum()

6

**Other reductions**

In [36]:
x = np.array([2,1, 3, 2])
x.min()

1

In [37]:
x.max()

3

In [38]:
x.argmin()# index of minimum element

1

In [39]:
x.argmax()# index of maximum element

2

**Logical Operations**

In [40]:
np.all([True, True, False])

False

In [41]:
np.any([True, False, False])

True

In [42]:
#Note: can be used for array comparisions
a = np.zeros((50, 50))
print(a)
print(a != 0)
np.any(a != 0)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]


False

In [55]:
print(a == a)
np.all(a == a)

[[ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 ...
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]]


True

**Statistics**

In [44]:
x = np.array([1, 2, 3])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()

2.0

In [45]:
print(y)

[[1 2 3]
 [5 6 1]]


In [46]:
y.sum()

18

In [48]:
y.mean()

3.0

In [49]:
y.mean(axis=0)

array([3., 4., 2.])

In [50]:
y.mean(axis=1)

array([2., 4.])

In [64]:
np.median(x)

1.5

In [51]:
np.median([3,5,1,2,7])

3.0

In [23]:
np.median([3,5,1,2,7,4])

3.5

In [54]:
y

array([[1, 2, 3],
       [5, 6, 1]])

In [55]:
np.median(y, axis=0) # last axis

array([3., 4., 2.])

In [57]:
np.median(y, axis=1)

array([2., 5.])

In [62]:
a = np.array([1,2,3,4,5]) #2,1
a.std()          # full population standard dev.

1.4142135623730951

In [64]:
a = np.array([10,2,30,4,50]) #9.2,17.2
print(a.mean())
a.std()

19.2


18.312837027615355

# Array Shape Manipulation

**Flattening**

In [24]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
a.ravel() #Return a contiguous flattened array. A 1-D array, containing the elements of the input, is returned. A copy is made only if needed.

[[1 2 3]
 [4 5 6]]


array([1, 2, 3, 4, 5, 6])

In [69]:
print(a)
print()
a.T #Transpose

[[1 2 3]
 [4 5 6]]



array([[1, 4],
       [2, 5],
       [3, 6]])

In [70]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

**Reshaping**

The inverse operation to flattening:

In [71]:
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [72]:
b = a.ravel()
print(b)

[1 2 3 4 5 6]


In [73]:
print(b.shape)

(6,)


In [76]:
b = b.reshape((2, 3))
b

array([[1, 2, 3],
       [4, 5, 6]])

**Adding a Dimension**

Indexing with the np.newaxis object allows us to add an axis to an array

newaxis is used to increase the dimension of the existing array by one more dimension, when used once. Thus,

1D array will become 2D array

2D array will become 3D array

3D array will become 4D array and so on

In [77]:
z = np.array([1, 2, 3])
z

array([1, 2, 3])

In [78]:
z[:, np.newaxis]

array([[1],
       [2],
       [3]])

**Dimension Shuffling**

In [28]:
a = np.arange(4)
print(a)
a = a.reshape(2,2)
print(a)
a.shape

[0 1 2 3]
[[0 1]
 [2 3]]


(2, 2)

In [29]:
a

array([[0, 1],
       [2, 3]])

**Resizing**

In [30]:
a = np.arange(4)
print(a)
a = a.reshape(3,2)
a

[0 1 2 3]


ValueError: cannot reshape array of size 4 into shape (3,2)

In [81]:
a = np.arange(4)
print(a)
a.resize((8,))
a

[0 1 2 3]


array([0, 1, 2, 3, 0, 0, 0, 0])

**Sorting Data**

In [89]:
#Sorting along an axis:
a = np.array([[5, 4, 6], [2, 3, 2]])
print(a)
b = np.sort(a)
b

[[5 4 6]
 [2 3 2]]


array([[4, 5, 6],
       [2, 2, 3]])