# The Numpy array object

# NumPy Arrays

In [1]:
import numpy as np
a = np.array([0, 1, 2, 3])
print(a)
print(type(a))

[0 1 2 3]
<class 'numpy.ndarray'>


In [61]:
list(range(10,20,2))

[10, 12, 14, 16, 18]

In [2]:
print(np.arange(10,20,2))

[10 12 14 16 18]


# 1. Creating arrays

** 1.1.  Manual Construction of arrays**

In [3]:
#1-D

a = np.array([0, 1, 2, 3])

a

array([0, 1, 2, 3])

In [4]:
#print dimensions

a.ndim

1

In [5]:
#shape

a.shape

(4,)

In [6]:
len(a)

4

In [7]:
# 2-D, 3-D....

b = np.array([[0, 1, 2], [3, 4, 5]])

b

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
b.ndim

2

In [9]:
b.shape

(2, 3)

In [71]:
len(b) #returns the size of the first dimention

2

** 1.2  Functions for creating arrays**

In [10]:
#using arrange function

# arange is an array-valued version of the built-in Python range function

a = np.arange(10) # 0.... n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
b = np.arange(1, 10, 2) #start, end (exclusive), step

b

array([1, 3, 5, 7, 9])

In [13]:
#using linspace

a = np.linspace(0, 1, 6) #start, end, number of points

a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [14]:
#common arrays

a = np.ones((4, 3))

a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
b = np.zeros((3, 3))

b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
c = np.eye(4)  #Return a 2-D array with ones on the diagonal and zeros elsewhere.

c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [83]:
d = np.eye(3, 2) #3 is number of rows, 2 is number of columns, index of diagonal start with 0

d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [18]:
#create array using diag function

a = np.diag([1, 2, 3, 4]) #construct a diagonal array.

a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [19]:
np.diag(a)   #Extract diagonal

array([1, 2, 3, 4])

In [22]:
#create array using random

#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
a = np.random.rand(4)

a

array([0.38469647, 0.10206514, 0.25620801, 0.93928901])

In [23]:
a = np.random.randn(4)#Return a sample (or samples) from the “standard normal” distribution.  ***Gausian***

a

array([-0.89302373, -0.3941244 , -0.2046358 ,  1.00923692])

# 2. Basic DataTypes

You may have noticed that, in some instances, array elements are displayed with a **trailing dot (e.g. 2. vs 2)**. This is due to a difference in the **data-type** used:

In [24]:
a = np.arange(10)
print(a)
a.dtype

[0 1 2 3 4 5 6 7 8 9]


dtype('int64')

In [25]:
#You can explicitly specify which data-type you want:

a = np.arange(10, dtype='float32')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [26]:
a.dtype

dtype('float32')

In [27]:
#The default data type is float for zeros and ones function

a = np.zeros((3, 3))

print(a)

a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

**other datatypes**

In [28]:
d = np.array([1+2j, 2+4j])   #Complex datatype

print(d.dtype)

complex128


In [29]:
b = np.array([True, False, True, False])  #Boolean datatype

print(b.dtype)

bool


# 3. Indexing and Slicing

**3.1 Indexing**

The items of an array can be accessed and assigned to the same way as other **Python sequences (e.g. lists)**:

In [30]:
a = np.arange(10)
print(a)
print(a[5])  #indices begin at 0, like other Python sequences (and C/C++)

[0 1 2 3 4 5 6 7 8 9]
5


In [32]:
# For multidimensional arrays, indexes are tuples of integers:

a = np.diag([1, 2, 3])
print(a)
print(a[2, 2]) #[0,2,0] [1]

[[1 0 0]
 [0 2 0]
 [0 0 3]]
3


In [33]:
print(a[1, 1])

2


In [34]:
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [35]:
a[2, 0] = 5 #assigning value

a

array([[1, 0, 0],
       [0, 2, 0],
       [5, 0, 3]])

**3.2 Slicing**

In [36]:
a = np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
a[1:8:2] # [startindex: endindex(exclusive) : step]

array([1, 3, 5, 7])

In [38]:
#we can also combine assignment and slicing:

a = np.arange(10)
print(a)
a[5:] = 10
a

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [39]:
a = np.arange(10)
b = np.arange(10,15)
print(a)
print(b)
a[5:] = b  #assigning

a

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14]


array([ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14])

# 4. Fancy Indexing

NumPy arrays can be indexed with slices, but also with boolean or integer arrays **(masks)**. This method is called **fancy indexing**. It creates copies not views.

**Using Boolean Mask**

In [42]:
a = np.random.randint(0, 20, 15)
a

array([ 0,  4, 16,  2,  8, 13,  2,  4,  1,  7,  7,  2, 19,  5,  7])

In [43]:
m = (a % 2 == 0)

In [44]:
extract_from_a = a[m]

extract_from_a

array([ 0,  4, 16,  2,  8,  2,  4,  2])

**Indexing with a mask can be very useful to assign a new value to a sub-array:**

In [45]:
a

array([ 0,  4, 16,  2,  8, 13,  2,  4,  1,  7,  7,  2, 19,  5,  7])

In [46]:
m = (a % 2 == 0)
a[m] = -1
a

array([-1, -1, -1, -1, -1, 13, -1, -1,  1,  7,  7, -1, 19,  5,  7])

**Indexing with an array of integers**

In [47]:
a = np.arange(0, 100, 10)

a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [48]:
#Indexing can be done with an array of integers, where the same index is repeated several time:

a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [49]:
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [145]:
# New values can be assigned

a[[9, 7]] = -200

a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])